name: Build and Release App

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build App
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.0.x"

      - name: Install dotnet version cli
        run: dotnet tool install -g dotnet-version-cli

      - name: Restore Packages
        run: dotnet restore

      - name: Build Release
        run: dotnet publish

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: XPSThermalTray
          path: bin\Release\net7.0-windows\win-x64\publish\
