name: Build and Release App

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build App
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.0.x"

      - name: Install dotnet version cli
        run: dotnet tool install -g dotnet-version-cli

      - uses: salsify/action-detect-and-tag-new-version@v2
        with:
          version-command: |
            dotnet version -o json | ConvertFrom-Json | Select-Object -ExpandProperty currentVersion
