name: Build and Release App

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build App
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.0.x"

      - name: Install dotnet version cli
        run: dotnet tool install -g dotnet-version-cli

      - name: Set app version env
        run: |
          $AppVer = dotnet version -o json | ConvertFrom-Json | Select-Object -ExpandProperty currentVersion
          "APP_VER=$AppVer" >> $env:GITHUB_ENV
          "V_APP_VER=v$AppVer" >> $env:GITHUB_ENV
          "RELEASE_NAME=Release $AppVer" >> $env:GITHUB_ENV

      - name: Restore Packages
        run: dotnet restore

      - name: Build Release
        run: dotnet publish

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.V_APP_VER }}
          release_name: ${{ env.RELEASE_NAME }}
          draft: false
          prerelease: false

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: XPSThermalTray
          path: bin\Release\net6.0-windows\win-x64\publish

      - name: Attach Artifact to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_path: bin\Release\net6.0-windows\win-x64\publish\MyApp.exe
          asset_name: MyApp.exe
          asset_content_type: application/octet-stream
          tag_name: v1.0.0
